# Dependencies
markdown:         kramdown
highlighter:      rouge

# Courses
collections:
  orf309:
    output: true
    output_ext: .html
  cos424:
    output: true
    output_ext: .html
  orf525:
    output: true
    output_ext: .html
